application: all-industrial-hrd
version: 5
runtime: python27
api_version: 1
threadsafe: no

handlers:

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/files/robots.txt
  upload: static/files/robots.txt
  
- url: /sitemap.xml
  static_files: static/files/sitemap.xml
  upload: static/files/sitemap.xml

- url: /search
  script: search.application

- url: /contact
  script: contact.application

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: .*
  script: index.application
  
libraries:
- name: webapp2
  version: "2.5.2"  
- name: django
  version: "1.2"